services:
  wiremock:
    image: "wiremock/wiremock:latest"
    volumes:
      - ./src/main/resources/mappings:/home/wiremock/mappings
    entrypoint: [ "/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose" ]
    ports:
      - "8443:8080"
